### ISSUE TITLE
Pin axe-core version to patch updates only (`~`)

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-nuget#114]
A user recently ran into a problem where [they installed an api at v4.7](https://github.com/dequelabs/axe-core-npm/issues/830) but got axe-core version v4.8 (causing some confusion on why rules weren't running that should have been). Turns out that we've been pinning to axe-core using `^` which allows minor updates. This goes against our goal of version locking the apis to the major and minor version of axe-core that is used in the api. 

We'll fix this by using `~` to patch pin our axe-core dependency.

**Comment by padmavemulapati** [comment]
Validated with the latest canary build avaible for axe-core-nuget (4.7.2-alpha.49)

<img width="982" alt="image" src="https://github.com/dequelabs/axe-core-nuget/assets/47409579/40268521-824b-4b6a-9c70-a0b4a9fbdec2">


For Axe-core-nuget we are not externally/intenally keeping package.json to specify the dependencies. But whatever the version for axe-core is updated , axe-core-nuget is holding strictly that version. (which will not allow minor updates)

Playwright Holding axe-core 4.8.2
![image](https://github.com/dequelabs/axe-core-nuget/assets/47409579/0a486d35-e8ba-4b81-9b6e-393643cf6673)

Selenium holding axe-core4.8.2
![image](https://github.com/dequelabs/axe-core-nuget/assets/47409579/9cd83200-a314-4282-848f-bc6de52fd02d)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-nuget_|
|**Version** | _4.7.2-alpha.49_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|
