### ISSUE TITLE
axe-core-nuget v4.8.0 - QA Needed

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-nuget#119]
Please QA axe-core-nuget v4.8.0 release candidate: https://github.com/dequelabs/axe-core-nuget/pull/117

**Comment by padmavemulapati** [comment]
@dequejenn  and @michael-siek  , No issues were observed on the fixes and features of [Release Candidate](https://github.com/dequelabs/axe-core-nuget/pull/117)
Done regression testing for all the available API's on both packages - Playwright-nuint and Selenium, everything looking good and seeing the expected results.
Here is the [test plan](https://dequeqa.testrail.io/index.php?/plans/view/2237) , can find the access credentials detials in the sign-off e-mail
