### ISSUE TITLE
Producing a report

### ISSUE THREAD

**Issue by fomnus** [dequelabs/axe-core-nuget#124]
If you have a feature or rule request for axe-core, please open an issue in https://github.com/dequelabs/axe-core.

## Which package is this feature for?
- [ ] Deque.AxeCore.Playwright

## Feature description
Is it possible to still produce a html report of a run? in the old nuget you could run

AxeHtmlReportOptions reportOptions = new(reportDir: "C:\myReport");
AxeResults axeResults = await page.RunAxe(reportOptions: reportOptions);

**Comment by dbjorge** [comment]
Deque maintains HTML reporting functionality as part of our [Axe DevTools](https://www.deque.com/axe/devtools/) products, so as part of porting the old C# libraries to Deque's namespace, the old library's HTML reporting functionality was split off to a different project.

We recommend [using the Axe DevTools Reporter from your C# tests](https://docs.deque.com/devtools-html/4.0.0/en/cs-generating-reports) for this - that's the HTML reporter we actively maintain.
