### ISSUE TITLE
Require QA consideration in PRs

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-nuget#138]
Set up https://github.com/dequelabs/axe-api-team-public/blob/main/.github/actions/semantic-pr-footer-v1 so it will block a PR that does not have at least one of the following:

- There is a link to a valid issue in the description of the PR
- The words "QA NOTES" appear in the description of the PR
- The words "QA NOT NEEDED" appear in the description of the PR

**Comment by padmavemulapati** [comment]
Verified Github actions, work flow is defined for QA-required actions, can find in the below link:

https://github.com/dequelabs/axe-core-nuget/blob/553042877ac538115daf1667d9ff0aea0c8b039c/.github/workflows/semantic-pr-footer.yml#L16

## Screenshot:

<img width="1258" alt="image" src="https://github.com/dequelabs/axe-core-nuget/assets/47409579/4c80fb7a-de37-4fb4-b0de-4a4db9b9cce1">
