### ISSUE TITLE
Pull in playwright dotnet 

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-nuget#5]
Migrate [axe playwright](https://github.com/IsaacWalker/PlaywrightAxeDotnet) into this repository.

**Comment by dbjorge** [comment]
If anyone except either Isaac (sole author of that repo) or Deque themselves is doing this, be careful to adhere to section 7 of Deque's CLA.

**Comment by dbjorge** [comment]
Done in #5 and #37
