### ISSUE TITLE
Add doc comments to all public types in commons project

### ISSUE THREAD

**Issue by dbjorge** [dequelabs/axe-core-nuget#60]
Right now a bunch of the types we pulled into Commons from the original selenium project are missing doc comments. Ideally we'd add these in so we're compliant with our own `CONTRIBUTING.md` guidelines and with the typical practices from `axe-core`. The Playwright equivalents generally do have those comments already, might make sense to do this together with #18

**Comment by lisli1** [comment]
Closed with #65
