### ISSUE TITLE
[Common] Bundle an axe-core implementation

### ISSUE THREAD

**Issue by dbjorge** [dequelabs/axe-core-nuget#8]
ie, set up the common package to embed a copy of `axe.min.js`. Preferably, use something similar to Playwright.Axe/Selenium.Axe where they have infrastructure to pull from the axe-core npm package rather than literally checking in a copy.

**To avoid MPL relicensing concerns, do not reusing any parts of Selenium.Axe's implementation that weren't solely authored by collaborators on this project.**

Probably pull in the existing implementation from Playwright.Axe instead.

**Comment by IsaacWalker** [comment]
This should be fairly straightforward. One concern we might consider is whether or not we allow overriding of the default bundled implementation.

Selenium.Axe currently supports it so it might break compatibility to not have it. One point against it may be, once a user overrides the default version then there is not really a guarantee of compatibility with the C# models.
