### ISSUE TITLE
QA needed for axe-core-nuget v4.7.1

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-nuget#92]
Release PR: https://github.com/dequelabs/axe-core-nuget/pull/91

QA needed for v4.7.1. Please close this ticket once QA has passed.

**Comment by padmavemulapati** [comment]
Closed [RC](https://github.com/dequelabs/axe-core-nuget/pull/104) via [ticket](https://github.com/dequelabs/axe-core-nuget/issues/103)
